---

### 6️⃣ `render.yaml`
```yaml
services:
  - type: web
    name: gateway-checker-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
